# Generated by Django 4.1.7 on 2023-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_category_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookscategory',
            name='alt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
