# Generated by Django 4.1.7 on 2023-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookscategory_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='alt',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='featuredbooks',
            name='alt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
